### ISSUE TITLE
Add "[Adblock Plus 2.0]" to the header of Anifiltrs to make it compatible with Opera's native adblocker?

### ISSUE THREAD

**Issue by sprite-1** [Karmesinrot/Anifiltrs#22]
When I try to load Anifiltrs.txt to the built in adblocker for Opera, t gives off a parse error

![image](https://user-images.githubusercontent.com/33685433/64224723-31e21200-cf0b-11e9-8f92-35495c6380b5.png)

But adding the `[Adblock Plus 2.0]` header at the top makes it accept it without issues. As far as I know the other adblockers like uBlock Origin don't complain about having this header, it just makes the list more compatible with ones with much stricter guidelines

**Comment by Karmesinrot** [comment]
I foresaw this question for quite some time; since I've used uBO syntax for most of the filters due to me not really intending to have the list used with ABP, having that header wouldn't make sense for `Anifiltrs` but it does makes sense only with `MAL-Sync UI`.

**Comment by sprite-1** [comment]
Oh I didn't realize this used uBlock Origin specific syntax, I did discover this list after installing MAL Sync

**Comment by Karmesinrot** [comment]
I will still add `[Adblock Plus 2.0]` to `MAL-Sync UI` to address elements of MAL-Sync broken by some filters of easylist and to also make it compatible with other adblockers that uses easylist.
