### ISSUE TITLE
Filter causing problem with MangaOnlineViewer script

### ISSUE THREAD

**Issue by hemlok89** [Karmesinrot/Anifiltrs#3]
Hello. I use this script to stop breakage of MalSync script. I also use another script for reading manga called [MangaOnlineViewer](https://github.com/TagoDR/MangaOnlineViewer). But this script always stops the second page of every manga from loading.

https://i.imgur.com/kvAH0eq.png

**Comment by Karmesinrot** [comment]
It works perfectly on my end. What does the uBlock Origin logger and your browser's web console say?

**Comment by hemlok89** [comment]
Thank you so much! I also identified Violentmonkey as the culprit last night after an exhausting troubleshooting. I really don't want to use Tampermonkey. Now it works fine.

**Comment by Karmesinrot** [comment]
For those with similar problems add `kissmanga.com#@#+js(setTimeout-defuser.js, (), 2000)` to your filters it's probably a better solution the solution in my previous comment.
