### ISSUE TITLE
Please add support to Animeflv.ru, Animeflv.la and Monoschinos.com

### ISSUE THREAD

**Issue by RedTestament** [Karmesinrot/Anifiltrs#30]
Fantastic collection of filters, very useful and thanks for your work and sharing them, can you please consider add to the filters the next sites? Thanks!!

https://animeflv.ru
https://animeflv.la
https://monoschinos.com/

**Comment by Karmesinrot** [comment]
I took a look a them and it seems they're pretty well covered by uBO lists. One possible filter is with animeflv.la which I'll add.
