### ISSUE TITLE
Cannot load episodes in 9anime

### ISSUE THREAD

**Issue by re11ding** [Karmesinrot/Anifiltrs#34]
As title suggests, going to any anime on the website with the main Anifiltrs enabled on uBlock Origin will prevent the capability of loading the video player and selector. You aren't even able to pick servers as it is blocking something crucial for the loader to work to begin with. 
Firefox 79 and uBlock Origin v.1.29.0. Disabled all other addons and determined this is not a conflict issue with another addon.

**Comment by Karmesinrot** [comment]
Ah I see it was due to a filter I've added a few hours ago to solve a redirect when opening the webconsole. I've removed the filter a few minutes ago after being given a report of breakage.

Fixed https://github.com/Karmesinrot/Anifiltrs/commit/843c742aeef2fdddc3886ec16a71ff12275d3227
