### ISSUE TITLE
Streamtape blocked in 9anime.

### ISSUE THREAD

**Issue by JJkeer** [Karmesinrot/Anifiltrs#38]
1. The Initial cause of the issue is this filter.
`||9anime.*^$document,csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.9anime.ru *.9anime.to *.akacdn.ru *.bunnycdn.ru *.googleapis.com *.gstatic.com www.google.com *.recaptcha.net *.disqus.com c.disquscdn.com hcaptcha.com assets.hcaptcha.com mcloud2.to mcloud.to cdnjs.cloudflare.com data: www.googletagmanager.com discordapp.com wss: realtime.services.disqus.com gateway.discord.gg ; frame-src disqus.com assets.hcaptcha.com mcloud.to mcloud2.to www.mp4upload.com www.google.com streamtape.com streamtape.net streamtape.xyz streamtape.to streamta.pe vidstream.pro ; img-src data: *,domain=~9anime.vip|~9anime.nl`

With the aforementioned filter active, it causes the act of blocking 
`||streamtape.*/ad.js$script,important`

Disabling the filter removes the blocking and Streamtape works fine.

Also would be nice if .vip and .nl would be removed but it's up to you :)

**Comment by Karmesinrot** [comment]
The second filter isn't really the primary cause rather it is a new streamtape domain which wasn't yet included on the CSP filter.

> Also would be nice if .vip and .nl would be removed but it's up to you :)
Those are added as exclusions(`domain=~example.com` vs inclusions `domain=example.com`) so the filter wouldn't affect those domains.
