### ISSUE TITLE
Gogoanime breaks/not works as intended due to some filters.

### ISSUE THREAD

**Issue by MysticsWinner** [Karmesinrot/Anifiltrs#39]
Gogoanime doesn't work, mainly the "container" containing the episode number, is blocked. For more ref, see the image.
![image](https://user-images.githubusercontent.com/70949976/110841716-43f4fb80-82cc-11eb-8cc7-7c2eae1e9abc.png)

Im a bit new, so Please excuse me if i made some mistakes in describing the issue. Its my first time with the Github

**Comment by Karmesinrot** [comment]
Gogoganime changed a resource thus creating a breakge due it not being included on the CSP filter.
#Im a bit new, so Please excuse me if i made some mistakes in describing the issue. Its my first time with the Github
Adding a url will be helpful for the next time.
