### ISSUE TITLE
Animepahe does not work - site gets stuck in Cloudflare loop while using filter

### ISSUE THREAD

**Issue by SilentSparrow02** [Karmesinrot/Anifiltrs#42]
Site URL: https://animepahe.ru/ (also .com and .org domains)
While using the filter, the browser cannot bypass cloudflare. I tried disabling the filter list in uBlock settings and the site opened fine.

If there are problems replicating the issue, clear animepahe cookies from your browser first.

Edit: Am using both the Anifiltrs and the Mal-Sync UI filter lists with Mal-Sync userscript

![image](https://user-images.githubusercontent.com/59610509/161081800-647afa13-2ebc-425d-bbb6-d42aaf0f5f43.png)

**Comment by Karmesinrot** [comment]
The loop doesn't happen on my end, though I know which filter may be causing it.

**Comment by SilentSparrow02** [comment]
Thanks, the site opens now. However, I've started to get pop-up ads on animepahe after the update.

**Comment by Karmesinrot** [comment]
That is a something the website has added recently which is quite unrelated to the first problem. I couldn't reproduce that at first since I was testing on animepahe.com which doesn't seem to have the same problems.
