### ISSUE TITLE
new vizcloud.site domain blocked by csp on 9anime

### ISSUE THREAD

**Issue by pepeloni-away** [Karmesinrot/Anifiltrs#43]
cannot use vidstream on 9anime because the new domain gets blocked
![Screenshot_20220720_212030_com kiwibrowser browser](https://user-images.githubusercontent.com/80548307/180054676-fcf0177a-4bd6-4537-80db-4594492a16da.jpg)

**Comment by Karmesinrot** [comment]
Thank You! I apologise for taking too long.
