### ISSUE TITLE
Enable syntax highlight

### ISSUE THREAD

**Issue by scripthunter7** [Karmesinrot/Anifiltrs#44]
Hello!

GitHub now supports syntax highlighting of adblock filter lists, but this requires the presence of the adblock agent. Demo: https://github.com/ameshkov/VscodeAdblockSyntax/blob/master/test_rules.txt

If you want to enable it, just insert the appropriate agent at the beginning of your filters. For example `[Adblock Plus 2.0]` / `[uBlock Origin]`

**Comment by Karmesinrot** [comment]
Ah thank you, I wasn't aware of that though I've been using the same syntax highlighting on VS Code for some number of years now.

**Comment by Karmesinrot** [comment]
Okay I've accepted the PR #46 , once again thank you.

**Comment by scripthunter7** [comment]
@Karmesinrot GitHub has been supporting adblock syntax highlighting since September 5th.

Further informations:
- Syntax highlighter repository: https://github.com/ameshkov/VscodeAdblockSyntax
- How Linguist works: https://github.com/github/linguist/blob/master/docs/how-linguist-works.md
- Linguist overrides: https://github.com/github/linguist/blob/master/docs/overrides.md
- Linguist commit: https://github.com/github/linguist/commit/e78ef71af3600f96b9a40a06511ebbe3797e7401
