### ISSUE TITLE
www1.gogoanime.ee broken

### ISSUE THREAD

**Issue by MolotovCherry** [Karmesinrot/Anifiltrs#45]
Get a "this content is blocked" message. Works fine when I disable the filter.

The problem appears to be in the main filter "Anifiltrs — 🍱 Anime streaming & Manga reading"

![image](https://user-images.githubusercontent.com/13651622/188680026-f21f755b-1a8a-454c-9024-aa50099c4b30.png)

**Comment by ramonsantana** [comment]
Same here with https://gogoanime.tel

**Comment by ToxicSmurf** [comment]
I'm having this same issue. Is there a solution?
