### ISSUE TITLE
Redirected to homepage during video playback (zoro.to) Chromium Version 110.0.5481.100

### ISSUE THREAD

**Issue by ToxicSmurf** [Karmesinrot/Anifiltrs#47]
This issue has persisted for months. If "Anifiltrs — 🍱 Anime streaming & Manga reading" is enabled (ublock Origin) zoro.to will constantly redirect back to their homepage during video playback. The only working solution currently is to disable the filter list, but I was wondering if you had any suggestions. Can provide video/logs if requested.

**Comment by Karmesinrot** [comment]
Ah that is caused by filters used to make the web console usable on the page. The only solution is to have them not compile when uBO is not running as Chrome extension — which is an easy fix.

**Comment by ToxicSmurf** [comment]
An easy fix on the user end or for the dev?

**Comment by Karmesinrot** [comment]
Oh sorry, I made a typo on the commit.

**Comment by ToxicSmurf** [comment]
The problem was definitely solved for a few days, but as of yesterday it started recurring. It doesn't seem like a common issue and I don't want to keep bugging you, so I'm just going to move on, but I figured I'd let you know beforehand.

**Comment by Karmesinrot** [comment]
@ToxicSmurf actually no filter of mine gets for zoro gets parsed in chrome, so techincally none of my filters are used in chrome. For the life of me I couldn't reproduce what you described there in the latest comment — it seems to just randomly happen, though only in chrome. In short after the previous commit anything that happens in zoro using chrome isn't my fault anymore.
