### ISSUE TITLE
aniwave.to gets stuck on cloudflare challenge

### ISSUE THREAD

**Issue by tigrrlily** [Karmesinrot/Anifiltrs#49]
![image](https://github.com/Karmesinrot/Anifiltrs/assets/68269257/8b4b9770-34bb-4bd2-bc23-e671614ffc5a)
 This happens every few episodes, and always for the first time of the day I go to the site. I've tried adding @@||challenges.cloudflare.com as an exception filter and it still gets caught, but @@ on the entire filter does work.

**Comment by Karmesinrot** [comment]
Reopen this if anything happens.
