### ISSUE TITLE
Aniwave CSP breaks Cloudflare challenge

### ISSUE THREAD

**Issue by SuperStormer** [Karmesinrot/Anifiltrs#52]
The following error shows up on a Cloudflare challenge page:
![image](https://github.com/Karmesinrot/Anifiltrs/assets/41648788/d5677bf0-812f-4b13-9796-70f3c4f8a7c5)

Console:
![image](https://github.com/Karmesinrot/Anifiltrs/assets/41648788/df1f6f42-dc2f-4f10-8bc9-a7288c4a36f1)

Disabling the CSP fixes this issue.

**Comment by Karmesinrot** [comment]
I've been trying to reacreate this for days but can't seem to encouter it for some reason. I think I'll just add the blob then.

**Comment by Karmesinrot** [comment]
Just reopen this when something comes up.
